version: '3'
services:
  sut:
    build: .
    command:
      - /bin/bash
      - -c
      - |
        . /etc/profile.d/modules.sh
        module use /usr/share/modulefiles
        module load mpi/openmpi-x86_64
        python3 -c "import gpaw.mpi; print(gpaw.mpi.rank)"
